package com.dailycodebuffer.departmentservice.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
@Data   //we used lombok to create getter, setter and constructor
@AllArgsConstructor      // both this constructor will be generated by lombok
@NoArgsConstructor
public class Department {

    @Id     // my departmentId would be primary key and it will be autogenerated
    @GeneratedValue(strategy = GenerationType.AUTO)
    // we're creating different properties
    private Long departmentId;
    private String departmentName;
    private String departmentAddress;
    private String departmentCode;


}
